apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: sidecar
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  location: "spec.containers[name:networking]"
  parameters:
    assign:
      value:
        name: "networking"
        imagePullPolicy: Always
        image: docker.io/centos
        command: ["/bin/bash", "-c", "sleep INF"]