apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: pram-runasuser
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    namespaces: ["pramdev"] # Applying the rule to "pramdev" namespace for all pods
  location: "spec.containers[name:*].securityContext.runAsUser"
  parameters:
    pathTests:
    - subPath: "spec.containers[name:*].securityContext.runAsUser"
      condition: MustNotExist
    assign:
      value: 1000
---
apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: pram-runasuser-init
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    namespaces: ["pramdev"] # Applying the rule to "pramdev" namespace for all pods
  location: "spec.initContainers[name:*].securityContext.runAsUser"
  parameters:
    pathTests:
    - subPath: "spec.initContainers[name:*].securityContext.runAsUser"
      condition: MustNotExist
    assign:
      value: 1000